/**
 * test/leaf-backward-compat.test.ts — FR-11 backward-compat guard.
 *
 * For every PR that touches `src/mcp-server.ts` (this PRD applies to US-001,
 * US-004, US-005, US-006), this test must pass. It asserts that the 25
 * pre-PRD leaves' input/output shape is byte-identical to the baseline
 * captured at commit 0c104caa.
 *
 * What "shape" means here (PRD FR-11):
 *   - leaf name             (string)
 *   - leaf description      (string, byte-equal)
 *   - input schema keys     (sorted array, byte-equal set)
 *   - handler parameters    (sorted array, byte-equal set)
 *   - output shape kind     ('mcp_text' canonical shape)
 *
 * Out of scope (asserted NOT to be load-bearing):
 *   - line numbers in the source — they shift with every edit and the
 *     fixture records them only for human debugging.
 *
 * The fixture `test/fixtures/leaf-baseline-snapshot.json` was generated by
 * `scripts/gen-leaf-baseline.ts` against commit 0c104caa. The test re-parses
 * the current `src/mcp-server.ts` with the same parser and asserts equality.
 */

import assert from 'node:assert/strict';
import * as fs from 'node:fs';
import * as path from 'node:path';
import test from 'node:test';

const MCP_SERVER = path.resolve('src/mcp-server.ts');
const FIXTURE = path.resolve('test/fixtures/leaf-baseline-snapshot.json');

interface LeafMeta {
  name: string;
  line: number;
  description: string;
  inputKeys: string[];
  handlerParams: string[];
  outputShape: 'mcp_text' | 'unknown';
}

interface Fixture {
  schemaVersion: number;
  baselineCommit: string;
  generatedAt: string;
  description: string;
  baselineLeaves: string[];
  leaves: Record<string, LeafMeta>;
}

// --- parser (mirror of scripts/gen-leaf-baseline.ts) -----------------------

function extractDescription(configLines: string): string {
  const m = /description:\s*'((?:\\'|[^'])*)'/.exec(configLines);
  if (!m) return '';
  return m[1]!.replace(/\\'/g, "'").replace(/\\n/g, ' ');
}

function extractInputKeys(configLines: string): string[] {
  const keys: string[] = [];
  const re = /^\s{8}([a-zA-Z_][a-zA-Z0-9_]*)\s*:/gm;
  let m: RegExpExecArray | null;
  while ((m = re.exec(configLines)) !== null) {
    const k = m[1]!;
    if (k === 'description' || k === 'inputSchema') continue;
    keys.push(k);
  }
  return [...new Set(keys)].sort();
}

function extractHandlerParams(handlerWindow: string): string[] {
  const m = /async\s*\(\{([^}]*)\}\)/.exec(handlerWindow);
  if (!m) return [];
  const params = m[1]!.split(',').map(s => s.trim().split(/[:=]/)[0]!.trim()).filter(Boolean);
  return [...new Set(params)].sort();
}

function detectOutputShape(handlerWindow: string): 'mcp_text' | 'unknown' {
  if (/content:\s*\[\s*\{\s*type:\s*'text'/.test(handlerWindow)) return 'mcp_text';
  return 'unknown';
}

function parseLeaves(source: string): Map<string, LeafMeta> {
  const out = new Map<string, LeafMeta>();
  const lines = source.split('\n');
  const callRe = /server\.registerTool\(\s*$/;
  let i = 0;
  while (i < lines.length) {
    if (callRe.test(lines[i] ?? '')) {
      const nameLineIdx = i + 1;
      const nameLine = (lines[nameLineIdx] ?? '').trim();
      const nameMatch = /^'([a-z_0-9]+)',\s*$/.exec(nameLine);
      if (!nameMatch) { i++; continue; }
      const name = nameMatch[1]!;

      let depth = 0;
      let started = false;
      let j = nameLineIdx + 1;
      let configEnd = -1;
      for (; j < lines.length; j++) {
        const ln = lines[j] ?? '';
        for (const ch of ln) {
          if (ch === '{') { depth++; started = true; }
          else if (ch === '}') { depth--; if (started && depth === 0) { configEnd = j; break; } }
        }
        if (configEnd !== -1) break;
      }
      if (configEnd === -1) { i++; continue; }

      const configLines = lines.slice(nameLineIdx + 1, configEnd + 1).join('\n');
      const description = extractDescription(configLines);
      const inputKeys = extractInputKeys(configLines);
      const handlerWindow = lines.slice(configEnd + 1, Math.min(lines.length, configEnd + 20)).join('\n');
      const handlerParams = extractHandlerParams(handlerWindow);
      const outputShape = detectOutputShape(handlerWindow);

      out.set(name, { name, line: i + 1, description, inputKeys, handlerParams, outputShape });
      i = configEnd + 1;
    } else {
      i++;
    }
  }
  return out;
}

// --- tests -----------------------------------------------------------------

test('fixture exists and parses', () => {
  const raw = fs.readFileSync(FIXTURE, 'utf8');
  const fixture = JSON.parse(raw) as Fixture;
  assert.equal(fixture.schemaVersion, 1, 'fixture schemaVersion');
  assert.equal(fixture.baselineCommit, '0c104caa', 'fixture baselineCommit must match 0c104caa');
  assert.equal(fixture.baselineLeaves.length, 25, 'fixture must cover exactly 25 baseline leaves');
});

test('all 25 baseline leaves are still registered', () => {
  const fixture = JSON.parse(fs.readFileSync(FIXTURE, 'utf8')) as Fixture;
  const source = fs.readFileSync(MCP_SERVER, 'utf8');
  const current = parseLeaves(source);
  for (const name of fixture.baselineLeaves) {
    assert.ok(current.has(name), `baseline leaf "${name}" no longer registered in ${MCP_SERVER}`);
  }
});

test('baseline leaves have byte-identical inputKeys, handlerParams, outputShape, description', () => {
  const fixture = JSON.parse(fs.readFileSync(FIXTURE, 'utf8')) as Fixture;
  const source = fs.readFileSync(MCP_SERVER, 'utf8');
  const current = parseLeaves(source);

  for (const name of fixture.baselineLeaves) {
    const baseline = fixture.leaves[name]!;
    const live = current.get(name);
    assert.ok(live, `leaf "${name}" missing`);

    assert.deepEqual(
      live.inputKeys,
      baseline.inputKeys,
      `inputKeys changed for "${name}"`,
    );
    assert.deepEqual(
      live.handlerParams,
      baseline.handlerParams,
      `handlerParams changed for "${name}"`,
    );
    assert.equal(
      live.outputShape,
      baseline.outputShape,
      `outputShape changed for "${name}"`,
    );
    assert.equal(
      live.description,
      baseline.description,
      `description changed for "${name}"`,
    );
  }
});

test('baseline count: exactly 25 leaves tracked by fixture', () => {
  const fixture = JSON.parse(fs.readFileSync(FIXTURE, 'utf8')) as Fixture;
  const tracked = Object.keys(fixture.leaves);
  assert.equal(tracked.length, 25);
  for (const name of tracked) {
    assert.ok(fixture.baselineLeaves.includes(name), `${name} in leaves but not baselineLeaves`);
  }
});

test('session_scratchpad is registered as a NEW tool (not in baseline)', () => {
  // Per the task spec: "The new tool session_scratchpad is NOT in the baseline
  // (it's new)." This guards against accidentally regressing the new tool by
  // failing the assertion if session_scratchpad gets conflated with the baseline.
  const fixture = JSON.parse(fs.readFileSync(FIXTURE, 'utf8')) as Fixture;
  assert.ok(!fixture.baselineLeaves.includes('session_scratchpad'),
    'session_scratchpad must NOT be in the baseline fixture (it is a new tool)');

  const source = fs.readFileSync(MCP_SERVER, 'utf8');
  const current = parseLeaves(source);
  assert.ok(current.has('session_scratchpad'),
    'session_scratchpad must be registered in src/mcp-server.ts');
});

test('summary: 25 baseline leaves present with byte-identical shape', () => {
  const fixture = JSON.parse(fs.readFileSync(FIXTURE, 'utf8')) as Fixture;
  const source = fs.readFileSync(MCP_SERVER, 'utf8');
  const current = parseLeaves(source);
  const matches: string[] = [];
  const mismatches: string[] = [];
  for (const name of fixture.baselineLeaves) {
    const baseline = fixture.leaves[name]!;
    const live = current.get(name);
    if (!live) { mismatches.push(`${name}: missing`); continue; }
    const ok =
      JSON.stringify(live.inputKeys) === JSON.stringify(baseline.inputKeys) &&
      JSON.stringify(live.handlerParams) === JSON.stringify(baseline.handlerParams) &&
      live.outputShape === baseline.outputShape &&
      live.description === baseline.description;
    if (ok) matches.push(name);
    else mismatches.push(name);
  }
  // Log the summary so failures show up clearly.
  // eslint-disable-next-line no-console
  console.log(`[backward-compat] matches=${matches.length}/25 mismatches=${mismatches.length} (${mismatches.join(', ') || 'none'})`);
  assert.equal(mismatches.length, 0, `mismatched leaves: ${mismatches.join(', ')}`);
  assert.equal(matches.length, 25);
});

test('additive growth allowed: every baseline leaf still present, current count >= 25', () => {
  // US-004 (Sprint 3) adds 2 new meta-tools (audit_symbol + plan_refactor)
  // and US-006 (Sprint 4) will add more. Per FR-11 we cannot REMOVE a
  // baseline leaf or CHANGE its input/output shape, but we CAN add new
  // tool registrations. This test asserts the additive-growth rule:
  //   - every baseline leaf is still present with byte-equal shape (above),
  //   - the current total tool count is at least the baseline 25.
  const fixture = JSON.parse(fs.readFileSync(FIXTURE, 'utf8')) as Fixture;
  const source = fs.readFileSync(MCP_SERVER, 'utf8');
  const current = parseLeaves(source);
  for (const name of fixture.baselineLeaves) {
    assert.ok(current.has(name), `baseline leaf "${name}" missing from current ${MCP_SERVER}`);
  }
  assert.ok(
    current.size >= fixture.baselineLeaves.length,
    `expected at least ${fixture.baselineLeaves.length} registered tools, found ${current.size}`,
  );
});

test('US-004 meta-tools are registered as new tools (additive)', () => {
  // Spot-check that the Sprint 3 additions are present in src/mcp-server.ts.
  // This guards against accidentally deleting a new tool by failing the
  // assertion if either meta-tool is missing.
  const source = fs.readFileSync(MCP_SERVER, 'utf8');
  const current = parseLeaves(source);
  for (const name of ['audit_symbol', 'plan_refactor']) {
    assert.ok(current.has(name), `US-004 meta-tool "${name}" must be registered in ${MCP_SERVER}`);
  }
});

test('additive growth: current.size === 70 (parser-derived exact count after Sprint 8)', () => {
  // ACTUAL_COUNT is the exact number of leaves the parser below discovers in
  // src/mcp-server.ts. It is intentionally an `===` equality (not `>=`) so
  // accidental additions or removals fail this test — the old `>= 29`
  // formula passed trivially because the real count is 70.
  //
  // Composition (Sprint 8 snapshot, parser-based):
  //   baseline 25 (FR-11 fixture, byte-equal)
  //   + US-004 Sprint 3   = 2  (audit_symbol, plan_refactor)
  //   + US-005 Sprint 4   = 2  (trace_workflow, collaborate)
  //   + US-006 Sprint 4   = 2  (session_status, run_intent)
  //   + Sprint 8 US-001   = 1  (review_pr)
  //   + cognition-layer tools shipped across Sprints 1-4 (~38) such as
  //     index_project, query_project, expand_graph, get_symbol, repo_map,
  //     smart_query, render_behavior, validate_architecture, etc.
  //   = 70 total
  //
  // If you add a new tool, update ACTUAL_COUNT and add a spot-check test
  // mirroring the existing US-004 / US-005 / US-006 style.
  const ACTUAL_COUNT = 70;
  const fixture = JSON.parse(fs.readFileSync(FIXTURE, 'utf8')) as Fixture;
  const source = fs.readFileSync(MCP_SERVER, 'utf8');
  const current = parseLeaves(source);
  for (const name of fixture.baselineLeaves) {
    assert.ok(current.has(name), `baseline leaf "${name}" missing`);
  }
  assert.equal(
    current.size,
    ACTUAL_COUNT,
    `expected exactly ${ACTUAL_COUNT} registered tools (parser-derived), found ${current.size}. ` +
      `If you added/removed a tool intentionally, update ACTUAL_COUNT and the spot-check tests below.`,
  );
});

test('US-005: trace_workflow tool is registered (additive)', () => {
  // Sprint 4 US-005 P3b superpowered tool. Spot-check the parser
  // discovers the registration in src/mcp-server.ts. Fails the test if
  // the new tool is missing or mis-registered.
  const source = fs.readFileSync(MCP_SERVER, 'utf8');
  const current = parseLeaves(source);
  assert.ok(current.has('trace_workflow'), 'US-005 meta-tool "trace_workflow" must be registered in src/mcp-server.ts');
});

test('US-005: collaborate tool is registered (additive)', () => {
  // Sprint 4 US-005 P3b goal-shaped entry point. Spot-check the parser
  // discovers the registration in src/mcp-server.ts. Fails the test if
  // the new tool is missing or mis-registered.
  const source = fs.readFileSync(MCP_SERVER, 'utf8');
  const current = parseLeaves(source);
  assert.ok(current.has('collaborate'), 'US-005 meta-tool "collaborate" must be registered in src/mcp-server.ts');
});

test('US-006: session_status tool is registered (additive)', () => {
  // Sprint 4 US-006 P4 read-only inspector (FR-9). Spot-check the
  // parser discovers the registration in src/mcp-server.ts. Fails the
  // test if the new tool is missing or mis-registered.
  const source = fs.readFileSync(MCP_SERVER, 'utf8');
  const current = parseLeaves(source);
  assert.ok(current.has('session_status'), 'US-006 read-only tool "session_status" must be registered in src/mcp-server.ts');
});

test('US-006: run_intent tool is registered (additive)', () => {
  // Sprint 4 US-006 P4 goal-shaped entry point (FR-8). The companion
  // to `collaborate`: takes a registered intent name (audit, onboard,
  // refactor, debug, release-prep) and runs the pre-declared DAG
  // directly. Spot-check the parser discovers the registration in
  // src/mcp-server.ts. Fails the test if the new tool is missing or
  // mis-registered.
  const source = fs.readFileSync(MCP_SERVER, 'utf8');
  const current = parseLeaves(source);
  assert.ok(current.has('run_intent'), 'US-006 goal-shaped tool "run_intent" must be registered in src/mcp-server.ts');
});

test('Sprint 8: review_pr tool is registered (additive)', () => {
  // Sprint 8 US-001 PR review combo tool. Fuses git_semantic_change_graph
  // + per-symbol audit_symbol + semantic_duplicates + architecture_drift +
  // constraint_violations + composite blast radius into a single
  // Block/Review/Pass merge-decision ToolResult. Mirrors the existing
  // US-006 spot-check style. Fails the test if review_pr gets dropped or
  // mis-registered.
  const source = fs.readFileSync(MCP_SERVER, 'utf8');
  const current = parseLeaves(source);
  assert.ok(current.has('review_pr'), 'Sprint 8 PR-review tool "review_pr" must be registered in src/mcp-server.ts');
});